export interface NBRForm {
  id: string;
  category: 'INCOME_TAX' | 'VAT';
  name: string;
  nameBn: string;
  description?: string;
}

export const INCOME_TAX_FORMS: NBRForm[] = [
  { id: 'IT-11GA-2023', category: 'INCOME_TAX', name: 'Individual Income Tax Return', nameBn: 'আইটি-১১গা (২০২৩): ব্যক্তিশ্রেণীর করদাতার রিটার্ন' },
  { id: 'IT-GHA-2023', category: 'INCOME_TAX', name: 'One Page Individual Return', nameBn: 'আইটি-ঘ (২০২৩): এক পাতার আয়কর রিটার্ন' },
  { id: 'IT-11CHA-2023', category: 'INCOME_TAX', name: 'Return for non-individual & non-companies', nameBn: 'আইটি-১১চ (২০২৩): ব্যক্তি ও কোম্পানি ব্যতীত অন্য সত্তার রিটার্ন' },
  { id: 'IT-11GHA-2023', category: 'INCOME_TAX', name: 'Company Tax Return', nameBn: 'আইটি-১১ঘ (২০২৩): কোম্পানি করদাতার রিটার্ন' },
  { id: 'IT-11CHA-2016', category: 'INCOME_TAX', name: 'Legacy Return (Non-individual)', nameBn: 'আইটি-১১চ (২০১৬): অ-ব্যক্তি করদাতার রিটার্ন' },
  { id: 'IT-10B-2016', category: 'INCOME_TAX', name: 'Statement of assets, liabilities and expenses', nameBn: 'আইটি-১০বি (২০১৬): সম্পদ, দায় ও ব্যয়ের বিবরণী' },
  { id: 'IT-10BB-2016', category: 'INCOME_TAX', name: 'Statement of lifestyle-related expenses', nameBn: 'আইটি-১০বিবি (২০১৬): জীবনযাত্রার মান সংশ্লিষ্ট ব্যয়ের বিবরণী' },
  { id: 'IT-124-2023', category: 'INCOME_TAX', name: 'IT-124 (2023 Version)', nameBn: 'আইটি-১২৪ (২০২৩)' },
  { id: 'IT-90-2023', category: 'INCOME_TAX', name: 'IT-90 (2023 Version)', nameBn: 'আইটি-৯০ (২০২৩)' },
  { id: 'IT-86-2023', category: 'INCOME_TAX', name: 'IT-86 (2023 Version)', nameBn: 'আইটি-৮৬ (২০২৩)' },
  { id: 'IT-57-2023', category: 'INCOME_TAX', name: 'IT-57 (2023 Version)', nameBn: 'আইটি-৫৭ (২০২৩)' },
  { id: 'IT-15-2023', category: 'INCOME_TAX', name: 'IT-15 (2023 Version)', nameBn: 'আইটি-১৫ (২০২৩)' },
  { id: 'IT-13-2023', category: 'INCOME_TAX', name: 'IT-13 (2023 Version)', nameBn: 'আইটি-১৩ (২০২৩)' },
  { id: 'IT-10-2023', category: 'INCOME_TAX', name: 'IT-10 (2023 Version)', nameBn: 'আইটি-১০ (২০২৩)' },
  { id: 'Schedule-24A', category: 'INCOME_TAX', name: 'Schedule 24A: Salary Income', nameBn: 'তফশিল ২৪ক: বেতন হইতে আয়' },
  { id: 'Schedule-24B', category: 'INCOME_TAX', name: 'Schedule 24B: House Property Income', nameBn: 'তফশিল ২৪খ: গৃহ-সম্পত্তি হইতে আয়' },
  { id: 'Schedule-24C', category: 'INCOME_TAX', name: 'Schedule 24C: Business or Profession Income', nameBn: 'তফশিল ২৪গ: ব্যবসা বা পেশা হইতে আয়' },
  { id: 'Schedule-24D', category: 'INCOME_TAX', name: 'Schedule 24D: Tax Rebate/Credit', nameBn: 'তফশিল ২৪ঘ: কর রেয়াত/ট্যাক্স ক্রেডিট' },
  { id: 'TDS-Source-Collected', category: 'INCOME_TAX', name: 'TDS Certificate (collected)', nameBn: 'উৎস হতে কর সংগ্রহের সনদ' },
  { id: 'TDS-Source-Deducted', category: 'INCOME_TAX', name: 'TDS Certificate (deducted)', nameBn: 'উৎস হতে কর কর্তনের সনদ' },
  { id: 'Monthly-Salary-TDS', category: 'INCOME_TAX', name: 'Monthly Statement (Salary TDS)', nameBn: 'বেতন হতে মাসিক কর কর্তনের বিবরণী' },
  { id: 'Monthly-Statement-Deduction', category: 'INCOME_TAX', name: 'Monthly Statement (Deduction/Collection)', nameBn: 'মাসিক কর কর্তন বা সংগ্রহের বিবরণী' },
  { id: 'Section-108-Statement', category: 'INCOME_TAX', name: 'Statement under Section 108', nameBn: 'ধারা ১০৮ এর অধীনে বিবরণী (বেতন পরিশোধ)' },
  { id: 'IT-ETIN-REG', category: 'INCOME_TAX', name: 'e-TIN Registration Form', nameBn: 'ই-টিআইএন নিবন্ধন ফর্ম' },
  { id: 'Return-Withholding-75A', category: 'INCOME_TAX', name: 'Return for Withholding Taxes (s.75A)', nameBn: 'উৎস কর কর্তনের রিটার্ন (ধারা ৭৫এ)' },
  { id: 'IT-11CHA-3Lakh', category: 'INCOME_TAX', name: 'IT-11CHA (Income up to 3 Lakh)', nameBn: 'আইটি-১১চ (৩ লক্ষ টাকা পর্যন্ত আয়)' },
];

export const VAT_FORMS: NBRForm[] = [
  { id: 'MUSOK-2.1', category: 'VAT', name: 'VAT Registration Application', nameBn: 'মূসক-২.১: ভ্যাট নিবন্ধন/টার্নওভার কর তালিকাভুক্তি' },
  { id: 'MUSOK-2.3', category: 'VAT', name: 'VAT Online Registration', nameBn: 'মূসক-২.৩: ভ্যাট অনলাইন নিবন্ধন' },
  { id: 'MUSOK-2.4', category: 'VAT', name: 'Suspension/Cancellation Registration', nameBn: 'মূসক-২.৪: নিবন্ধন/তালিকাভুক্তি স্থগিত বা বাতিল' },
  { id: 'MUSOK-2.5', category: 'VAT', name: 'Change Notification Post-registration', nameBn: 'মূসক-২.৫: নিবন্ধন পরবর্তী পরিবর্তন বিজ্ঞপ্তি' },
  { id: 'MUSOK-3.1', category: 'VAT', name: 'Application for VAT Agent Certificate', nameBn: 'মূসক-৩.১: ভ্যাট এজেন্ট সার্টিফিকেটের আবেদন' },
  { id: 'MUSOK-3.2', category: 'VAT', name: 'VAT Agent Certificate', nameBn: 'মূসক-৩.২: ভ্যাট এজেন্ট সার্টিফিকেট' },
  { id: 'MUSOK-3.3', category: 'VAT', name: 'Power of Attorney to VAT Agent', nameBn: 'মূসক-৩.৩: ভ্যাট এজেন্টের আমমোক্তারনামা' },
  { id: 'MUSOK-4.1', category: 'VAT', name: 'Application for Advance Tax Refund', nameBn: 'মূসক-৪.১: আগাম কর ফেরতের আবেদন' },
  { id: 'MUSOK-4.2', category: 'VAT', name: 'Application for Business Transfer', nameBn: 'মূসক-৪.২: চলমান ব্যবসা হস্তান্তরের আবেদন' },
  { id: 'MUSOK-4.3', category: 'VAT', name: 'Input-Output Coefficient Declaration', nameBn: 'মূসক-৪.৩: উপকরণ-উৎপাদ সহগ ঘোষণা' },
  { id: 'MUSOK-4.4', category: 'VAT', name: 'Disposal of Unused Inputs', nameBn: 'মূসক-৪.৪: অব্যবহৃত উপকরণ নিষ্পত্তির আবেদন' },
  { id: 'MUSOK-4.5', category: 'VAT', name: 'Disposal of Damaged Goods', nameBn: 'মূসক-৪.৫: ক্ষতিগ্রস্ত পণ্য নিষ্পত্তির আবেদন' },
  { id: 'MUSOK-6.1', category: 'VAT', name: 'Purchase Account Book', nameBn: 'মূসক-৬.১: ক্রয় হিসাবপুস্তক' },
  { id: 'MUSOK-6.2', category: 'VAT', name: 'Sales Account Book', nameBn: 'মূসক-৬.২: বিক্রয় হিসাবপুস্তক' },
  { id: 'MUSOK-6.2.1', category: 'VAT', name: 'Purchase-Sales Account Book', nameBn: 'মূসক-৬.২.১: ক্রয়-বিক্রয় হিসাবপুস্তক' },
  { id: 'MUSOK-6.3', category: 'VAT', name: 'Tax Invoice (Challan)', nameBn: 'মূসক-৬.৩: কর চালানপত্র' },
  { id: 'MUSOK-6.4', category: 'VAT', name: 'Contract-based Production Challan', nameBn: 'মূসক-৬.৪: চুক্তিভিত্তিক উৎপাদন চালান' },
  { id: 'MUSOK-6.5', category: 'VAT', name: 'Goods Transfer Challan (Central)', nameBn: 'মূসক-৬.৫: পণ্য স্থানান্তর চালান (কেন্দ্রীয়)' },
  { id: 'MUSOK-6.6', category: 'VAT', name: 'TDS Certificate (VAT)', nameBn: 'মূসক-৬.৬: উৎসে কর কর্তন সনদপত্র' },
  { id: 'MUSOK-6.7', category: 'VAT', name: 'Credit Note', nameBn: 'মূসক-৬.৭: ক্রেডিট নোট' },
  { id: 'MUSOK-6.8', category: 'VAT', name: 'Debit Note', nameBn: 'মূসক-৬.৮: ডেবিট নোট' },
  { id: 'MUSOK-6.9', category: 'VAT', name: 'Turnover Tax Challan', nameBn: 'মূসক-৬.৯: টার্নওভার কর চালান' },
  { id: 'MUSOK-6.10', category: 'VAT', name: 'Data of Purchase/Sale > 2 Lakh', nameBn: 'মূসক-৬.১০: ২ লক্ষাধিক টাকার ক্রয়/বিক্রয় তথ্য' },
  { id: 'MUSOK-7.1', category: 'VAT', name: 'Supplementary Duty Adjustment', nameBn: 'মূসক-৭.১: সম্পূরক শুল্ক সমন্বয় আবেদন' },
  { id: 'MUSOK-9.1', category: 'VAT', name: 'VAT Return (Dakhilpatra)', nameBn: 'মূসক-৯.১: ভ্যাট রিটার্ন (দাখিলপত্র)' },
  { id: 'MUSOK-9.2', category: 'VAT', name: 'Turnover Tax Return', nameBn: 'মূসক-৯.২: টার্নওভার কর রিটার্ন' },
  { id: 'MUSOK-9.3', category: 'VAT', name: 'Late Return Submission Application', nameBn: 'মূসক-৯.৩: বিলম্বে রিটার্ন দাখিলের আবেদন' },
  { id: 'MUSOK-9.4', category: 'VAT', name: 'Amended Return Application', nameBn: 'মূসক-৯.৪: সংশোধিত রিটার্ন দাখিলের আবেদন' },
  { id: 'MUSOK-10.1', category: 'VAT', name: 'Tax Refund Diplomatic/Intl Org', nameBn: 'মূসক-১০.১: কূটনৈতিক/আন্তর্জাতিক সংস্থার কর ফেরত আবেদন' },
  { id: 'MUSOK-10.2', category: 'VAT', name: 'VAT Refund Certificate (Foreign Tourists)', nameBn: 'মূসক-১০.২: বিদেশি পর্যটকদের জন্য ভ্যাট ফেরত সনদ' },
  { id: 'MUSOK-10.3', category: 'VAT', name: 'Apprv Tourist VAT Refund Cert', nameBn: 'মূসক-১০.৩: পর্যটক ভ্যাট ফেরত সনদ ইস্যুর অনুমোদনের আবেদন' },
  { id: 'MUSOK-11.1', category: 'VAT', name: 'Notice Delayed Return Submission', nameBn: 'মূসক-১১.১: বিলম্বে রিটার্ন দাখিলের নোটিশ' },
  { id: 'MUSOK-11.2', category: 'VAT', name: 'Notice Tax Assessment', nameBn: 'মূসক-১১.২: কর নির্ধারণের নোটিশ' },
  { id: 'MUSOK-12.1', category: 'VAT', name: 'Authorization Entry/Search/Seizure', nameBn: 'মূসক-১২.১: প্রবেশ, তল্লাশি ও জব্দের ক্ষমতা প্রদান' },
  { id: 'MUSOK-12.3', category: 'VAT', name: 'Seizure List (Jabdo Talika)', nameBn: 'মূসক-১২.৩: জব্দ তালিকা (ক্রোকি)' },
  { id: 'MUSOK-12.6', category: 'VAT', name: 'Evasion/Tax Fraud Case', nameBn: 'মূসক-১২.৬: ফাঁকি/কর জালিয়াতি মামলা' },
  { id: 'MUSOK-12.9', category: 'VAT', name: 'Order Freeze Bank Account', nameBn: 'মূসক-১২.৯: ব্যাংক হিসাব জব্দের আদেশ' },
  { id: 'MUSOK-12.12', category: 'VAT', name: 'Show Cause Notice', nameBn: 'মূসক-১২.১২: কারণ দর্শানো নোটিশ' },
  { id: 'MUSOK-13.1', category: 'VAT', name: 'Initial Supervised Supply Report', nameBn: 'মূসক-১৩.১: তত্ত্বাবধানকৃত সরবরাহের প্রাথমিক রিপোর্ট' },
  { id: 'MUSOK-13.2', category: 'VAT', name: 'Daily Supervised Supply Report', nameBn: 'মূসক-১৩.২: তত্ত্বাবধানকৃত সরবরাহের দৈনিক রিপোর্ট' },
  { id: 'MUSOK-13.3', category: 'VAT', name: 'Final Supervised Supply Report', nameBn: 'মূসক-১৩.৩: তত্ত্বাবধানকৃত সরবরাহের চূড়ান্ত রিপোর্ট' },
  { id: 'MUSOK-14.1', category: 'VAT', name: 'Arrear Tax Recovery Certificate', nameBn: 'মূসক-১৪.১: বকেয়া কর আদায়ের সার্টিফিকেট' },
  { id: 'MUSOK-14.2', category: 'VAT', name: 'State Dues Recovery Notice', nameBn: 'মূসক-১৪.২: সরকারি পাওনা আদায়ের নোটিশ' },
  { id: 'MUSOK-16.1', category: 'VAT', name: 'Notice for Sworn Statement', nameBn: 'মূসক-১৬.১: হলফনামার নোটিশ' },
  { id: 'MUSOK-17.1', category: 'VAT', name: 'Application for ADR', nameBn: 'মূসক-১৭.১: বিকল্প বিরোধ নিষ্পত্তির (ADR) আবেদন' },
  { id: 'MUSOK-17.3', category: 'VAT', name: 'Settlement Conditions', nameBn: 'মূসক-১৭.৩: নিষ্পত্তির শর্তাবলী' },
  { id: 'MUSOK-18.1', category: 'VAT', name: 'Application VAT Consultant License', nameBn: 'মূসক-১৮.১: ভ্যাট কনসালট্যান্ট লাইসেন্সের আবেদন' },
  { id: 'MUSOK-18.1A', category: 'VAT', name: 'VAT Consultant License', nameBn: 'মূসক-১৮.১ক: ভ্যাট কনসালট্যান্ট লাইসেন্স' },
  { id: 'MUSOK-18.2', category: 'VAT', name: 'Certified Copy Application', nameBn: 'মূসক-১৮.২: দলিলের জাবেদা নকলের আবেদন' },
  { id: 'MUSOK-18.3', category: 'VAT', name: 'Application VAT Clearance Certificate', nameBn: 'মূসক-১৮.৩: ভ্যাট ক্লিয়ারেন্স সার্টিফিকেটের আবেদন' },
  { id: 'MUSOK-18.4', category: 'VAT', name: 'VAT Clearance Certificate', nameBn: 'মূসক-১৮.৪: ভ্যাট ক্লিয়ারেন্স সার্টিফিকেট' },
  { id: 'MUSOK-18.5', category: 'VAT', name: 'VAT Honor Certificate', nameBn: 'মূসক-১৮.৫: ভ্যাট সম্মাননা সার্টিফিকেট' },
  { id: 'MUSOK-18.6', category: 'VAT', name: 'Certificate Adjustment Dep 1991', nameBn: 'মূসক-১৮.৬: ১৯৯১ সালের ভ্যাট সমন্বয়ের সার্টিফিকেট' },
];

export const ALL_FORMS = [...INCOME_TAX_FORMS, ...VAT_FORMS];
